### ISSUE TITLE
【idea】resultに遷移したときにお菓子が溢れ出すアニメーション

### ISSUE THREAD

**Issue by Meow520** [Doer-org/hack-camp_vol4_2022#17]

**Comment by Meow520** [comment]
resultに遷移したときにお菓子が溢れ出すアニメーション

**Comment by Meow520** [comment]
イラストやには頼らず画像のお菓子を溢れ出させたい。

**Comment by mahiro72** [comment]
お菓子がゆらゆらとか

あみだくじの箱ふりふりでもいいので

実装お願いしたいです....！！！！

@nisi0929

**Comment by miso-devel** [comment]
できた！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
