### ISSUE TITLE
【idea】お菓子を宝箱にドラッグ&ドロップしたら、いいね判定にしたい

### ISSUE THREAD

**Issue by mahiro72** [Doer-org/hack-camp_vol4_2022#32]

**Comment by miso-devel** [comment]
- React-dnd（ドラッグ&ドロップライブラリ）を使う
   - 理由は最近までアップデートされてるからとドキュメントがあるから
   - https://zenn.dev/mtblue81/articles/98ae1a40266317
   - https://tech.hey.jp/entry/2021/03/09/131638
   - https://www.npmjs.com/package/react-dnd
- 実装方法としてはいいねボタンはいるかも
- 流れとしてはお菓子箱の中にお菓子をドラッグ&ドロップをする。その後、ボタンを押してドラッグされたお菓子のパラメーターを送る？？？？
