### ISSUE TITLE
【Todo】Form

### ISSUE THREAD

**Issue by miso-devel** [Doer-org/hack-camp_vol4_2022#39]

**Comment by miso-devel** [comment]
@hikari-8 
- [ ] Formの見た目を作ってもらいたいです！
- [ ] 実際にデータが送られてるようにもしてほしいです！！！
- [ ] Home.jsxをForm.jsxに直しておいてほしいです！（これは僕のミスですごめんなさい）

**Comment by hikari-8** [comment]
@nisi0929 了解です！ありがとうございます！
